projeto_dash/projeto_dash/urls.py
from app_dash import views
from django.urls import path

urlpatterns = [
path('', views.home, name='home'),
path('login_candidato/', views.login_candidato, name='login_candidato'),
path('login_empresa/', views.login_empresa, name='login_empresa'),
path('cadastro_candidato/', views.cadastro_candidato_view,
        name='cadastro_candidato'),
path('cadastro_empresa/', views.cadastro_empresa_view, name='cadastro_empresa'),
path('home_empresa/', views.pagina_apos_cadastro_empresa,
        name='pagina_apos_cadastro_empresa'),
path('home_candidato/', views.pagina_apos_cadastro_candidato,
        name='pagina_apos_cadastro_candidato'),
path('logout/', views.custom_logout, name='logout'),
path('vagas/', views.lista_vagas, name='lista_vagas'),
path('vagas/<int:vaga_id>/candidatos/',
        views.visualizar_candidatos, name='visualizar_candidatos'),
path('vagas/nova/', views.nova_vaga, name='nova_vaga'),
path('vagas/<int:vaga_id>/editar/', views.editar_vaga, name='editar_vaga'),
path('vagas/<int:vaga_id>/deletar/',
        views.deletar_vaga, name='deletar_vaga'),
path('vagas/<int:vaga_id>/candidatar/',
        views.candidatar_vaga, name='candidatar_vaga'),
path('desistir_vaga/<int:candidatura_id>/',
        views.desistir_vaga, name='desistir_vaga'),
path('vagas_criadas_por_mes/', views.vagas_criadas_por_mes, name='vagas_criadas_por_mes'),
path('candidatos_recebidos_por_mes/', views.candidatos_recebidos_por_mes, name='candidatos_recebidos_por_mes'),
]

projeto_dash/app_dash/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class UserProfile(models.Model):
    USER_TYPE_CHOICES = (
        ('C', 'Candidato'),
        ('E', 'Empresa'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(
        max_length=1, choices=USER_TYPE_CHOICES, default='C')

    def __str__(self):
        return self.user.username


class Empresa(models.Model):
    nome_empresa = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=14)

    def __str__(self):
        return self.nome_empresa


class Vaga(models.Model):
    FAIXA_SALARIAL_CHOICES = [
        ('1', 'Até 1.000'),
        ('2', 'De 1.000 a 2.000'),
        ('3', 'De 2.000 a 3.000'),
        ('4', 'Acima de 3.000'),
    ]
    ESCOLARIDADE_CHOICES = [
        ('EF', 'Ensino Fundamental'),
        ('EM', 'Ensino Médio'),
        ('TEC', 'Tecnólogo'),
        ('ES', 'Ensino Superior'),
        ('POS', 'Pós / MBA / Mestrado'),
        ('DOUT', 'Doutorado'),
    ]

    nome = models.CharField(max_length=255)
    faixa_salarial = models.CharField(
        max_length=1, choices=FAIXA_SALARIAL_CHOICES)
    requisitos = models.TextField()
    escolaridade_minima = models.CharField(
        max_length=4, choices=ESCOLARIDADE_CHOICES)

    def __str__(self):
        return self.nome

    def vagas_disponiveis(self, user):

        candidaturas = Candidato.objects.filter(
            user=user).values_list('vaga', flat=True)
        return Vaga.objects.exclude(pk__in=candidaturas)
    
    data_criacao = models.DateTimeField(default=timezone.now)


class Candidato(models.Model):
    PRETENSAO_SALARIAL_CHOICES = [
        ('1', 'Até 1.000'),
        ('2', 'De 1.000 a 2.000'),
        ('3', 'De 2.000 a 3.000'),
        ('4', 'Acima de 3.000'),
    ]

    EXPERIENCIA_CHOICES = [
        ('1', 'Sem Experiência'),
        ('2', 'Menos de 1 ano'),
        ('3', '1 a 3 anos'),
        ('4', '3 a 5 anos'),
        ('5', 'Mais de 5 anos'),
    ]

    ESCOLARIDADE_CHOICES = [
        ('EF', 'Ensino Fundamental'),
        ('EM', 'Ensino Médio'),
        ('TEC', 'Tecnólogo'),
        ('ES', 'Ensino Superior'),
        ('POS', 'Pós / MBA / Mestrado'),
        ('DOUT', 'Doutorado'),
    ]

    pretensao_salarial = models.CharField(
        max_length=1, choices=PRETENSAO_SALARIAL_CHOICES)
    experiencia = models.CharField(max_length=1, choices=EXPERIENCIA_CHOICES)
    escolaridade = models.CharField(max_length=4, choices=ESCOLARIDADE_CHOICES)
    perfil = models.TextField()
    vaga = models.ForeignKey(
        Vaga, on_delete=models.CASCADE, related_name='candidatos')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='candidaturas')
    pontuacao_faixa_salarial = models.IntegerField(default=0)
    pontuacao_escolaridade = models.IntegerField(default=0)
    pontuacao_total = models.IntegerField(default=0)
    data_candidatura = models.DateTimeField(default=timezone.now)
    

    def calcular_pontuacao_total(self):
        return self.pontuacao_faixa_salarial + self.pontuacao_escolaridade

    def __str__(self):
        return f"Candidato {self.user.email} para a vaga {self.vaga.nome}"

projeto_dash/app_dash/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count
from django.db.models.functions import TruncMonth
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .models import Candidato, Empresa, User, UserProfile, Vaga


def home(request):
    return render(request, 'home.html')

def vagas_criadas_por_mes(request):
    vagas_por_mes = Vaga.objects.annotate(mes_criacao=TruncMonth('data_criacao')) \
                                .values('mes_criacao') \
                                .annotate(count=Count('id'))

    data = [{'mes': item['mes_criacao'].strftime('%Y-%m'), 'count': item['count']} for item in vagas_por_mes]

    return JsonResponse(data, safe=False)

def candidatos_recebidos_por_mes(request):
    candidatos_por_mes = Candidato.objects.annotate(mes_candidatura=TruncMonth('data_candidatura')) \
                                        .values('mes_candidatura') \
                                        .annotate(count=Count('id'))

    data = [{'mes': item['mes_candidatura'].strftime('%Y-%m'), 'count': item['count']} for item in candidatos_por_mes]

    return JsonResponse(data, safe=False)


def lista_vagas(request):
    vagas = Vaga.objects.all()
    return render(request, "empresa/vagas/lista_vagas.html", {"vagas": vagas})


def visualizar_candidatos(request, vaga_id):
    vaga = get_object_or_404(Vaga, pk=vaga_id)
    candidatos = Candidato.objects.filter(vaga=vaga)

    for candidato in candidatos:
        candidato.pontuacao_total = candidato.pontuacao_faixa_salarial + \
            candidato.pontuacao_escolaridade

    return render(
        request, "empresa/vagas/visualizar_candidatos.html", {
            "vaga": vaga,
            "candidatos": candidatos,
        }
    )


def deletar_vaga(request, vaga_id):
    vaga = get_object_or_404(Vaga, pk=vaga_id)

    if request.method == 'POST':
        vaga.delete()
        return redirect('lista_vagas')

    return render(request, 'empresa/vagas/deletar_vaga.html', {'vaga': vaga})


def login_empresa(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            try:
                user_profile = UserProfile.objects.get(user=user)
            except UserProfile.DoesNotExist:
                error = "Usuário ou senha incorretos."
                return render(request, "empresa/login_empresa.html", {"error": error})

            if user_profile.user_type == 'E':
                login(request, user)
                return redirect("pagina_apos_cadastro_empresa")
            else:
                error = "Apenas empresas podem fazer login."
                return render(request, "empresa/login_empresa.html", {"error": error})
        else:
            error = "Usuário ou senha incorretos."
            return render(request, "empresa/login_empresa.html", {"error": error})

    return render(request, "empresa/login_empresa.html")


def login_candidato(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            try:
                user_profile = UserProfile.objects.get(user=user)
            except UserProfile.DoesNotExist:
                error = "Usuário ou senha incorretos."
                return render(request, "candidato/login_candidato.html", {"error": error})

            if user_profile.user_type == 'C':
                login(request, user)
                return redirect("pagina_apos_cadastro_candidato")
            else:
                error = "Apenas candidatos podem fazer login."
                return render(request, "candidato/login_candidato.html", {"error": error})
        else:
            error = "Usuário ou senha incorretos."
            return render(request, "candidato/login_candidato.html", {"error": error})

    return render(request, "candidato/login_candidato.html")


def cadastro_candidato_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        user_type = 'C'
        
        if User.objects.filter(username=username).exists():
            error = "Este nome de usuário já está sendo usado por outro usuário."
            return render(request, "cadastro/cadastro_candidato.html", {"error": error})

        if password1 != password2:
            return render(
                request,
                "cadastro/cadastro_candidato.html",
                {"error": "As senhas não coincidem."},
            )


        user = User.objects.create_user(
            username=username, password=password1)
        UserProfile.objects.create(user=user, user_type=user_type)

        return redirect("login_candidato")

    return render(request, "cadastro/cadastro_candidato.html")


def cadastro_empresa_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")
        nome_empresa = request.POST.get("nome_empresa")
        cnpj = request.POST.get("cnpj")

        if password1 != password2:
            return render(
                request,
                "cadastro/cadastro_empresa.html",
                {"error": "As senhas não coincidem."},
            )

        if User.objects.filter(username=username).exists():
            return render(
                request,
                "cadastro/cadastro_empresa.html",
                {"error": "Este e-mail já está sendo usado por outra empresa."},
            )

        user = User.objects.create_user(username=username, password=password1)
        empresa = Empresa.objects.create(nome_empresa=nome_empresa, cnpj=cnpj)

        user_profile = UserProfile.objects.create(user=user, user_type='E')

        return redirect("login_empresa")

    return render(request, "cadastro/cadastro_empresa.html")


def custom_logout(request):
    logout(request)
    return redirect('home')


@login_required
def editar_vaga(request, vaga_id):
    vaga = get_object_or_404(Vaga, pk=vaga_id)

    if request.method == 'POST':
        nome = request.POST.get('nome')
        faixa_salarial = request.POST.get('faixa_salarial')
        requisitos = request.POST.get('requisitos')
        escolaridade_minima = request.POST.get('escolaridade_minima')

        vaga.nome = nome
        vaga.faixa_salarial = faixa_salarial
        vaga.requisitos = requisitos
        vaga.escolaridade_minima = escolaridade_minima

        vaga.save()

        candidatos = Candidato.objects.filter(vaga=vaga)
        pontuacao_escolaridade_dict = {
            'EF': 0,
            'EM': 1,
            'TEC': 2,
            'ES': 3,
            'POS': 4,
            'DOUT': 5,
        }

        for candidato in candidatos:
            candidato.pontuacao_faixa_salarial = 0
            if candidato.pretensao_salarial == vaga.faixa_salarial:
                candidato.pontuacao_faixa_salarial = 1

            pontuacao_escolaridade = 0
            if pontuacao_escolaridade_dict[candidato.escolaridade] >= pontuacao_escolaridade_dict[vaga.escolaridade_minima]:
                pontuacao_escolaridade = 1

            candidato.pontuacao_escolaridade = pontuacao_escolaridade
            candidato.pontuacao_total = candidato.pontuacao_faixa_salarial + pontuacao_escolaridade
            candidato.save()

        return redirect('lista_vagas')

    return render(request, 'empresa/vagas/editar_vaga.html', {'vaga': vaga})


@login_required
def pagina_apos_cadastro_empresa(request):
    vagas = Vaga.objects.all()

    empresa = Empresa.objects.first()
    
    return render(request, "empresa/home_empresa.html", {"vagas": vagas, "empresa": empresa})


@login_required
def pagina_apos_cadastro_candidato(request):
    vagas = Vaga.objects.all()

    vagas_candidatadas = Candidato.objects.filter(user=request.user)

    ids_vagas_candidatadas = vagas_candidatadas.values_list(
        'vaga__id', flat=True)

    vagas_disponiveis = vagas.exclude(id__in=ids_vagas_candidatadas)

    return render(request, "candidato/home_candidato.html", {"vagas": vagas_disponiveis, "vagas_candidatadas": vagas_candidatadas})


@login_required
def nova_vaga(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        faixa_salarial = request.POST.get('faixa_salarial')
        requisitos = request.POST.get('requisitos')
        escolaridade_minima = request.POST.get('escolaridade_minima')

        nova_vaga = Vaga.objects.create(
            nome=nome,
            faixa_salarial=faixa_salarial,
            requisitos=requisitos,
            escolaridade_minima=escolaridade_minima,
        )

        nova_vaga.save()

        return redirect('pagina_apos_cadastro_empresa')


    return render(request, 'empresa/vagas/nova_vaga.html')


@login_required
def desistir_vaga(request, candidatura_id):
    candidatura = get_object_or_404(
        Candidato, pk=candidatura_id, user=request.user)

    if request.method == 'POST':
        candidatura.delete()
        messages.success(request, 'Você desistiu da vaga com sucesso!')
        return redirect('pagina_apos_cadastro_candidato')

    return redirect('pagina_apos_cadastro_candidato')


@login_required
def candidatar_vaga(request, vaga_id):
    vaga = get_object_or_404(Vaga, pk=vaga_id)

projeto_dash/app_dash/templates/empresa/vagas/deletar_vaga.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1 class="display-4">Deletar Vaga: {{ vaga.nome }}</h1>
    <p>Você está prestes a deletar a vaga "<strong>{{ vaga.nome }}</strong>". Tem certeza de que deseja continuar?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Sim, Deletar Vaga</button>
    </form>

    <a href="{% url 'pagina_apos_cadastro_empresa' %}" class="btn btn-secondary">Voltar para a home</a>
</div>
{% endblock %}

projeto_dash/app_dash/templates/empresa/vagas/editar_vaga.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1 class="display-4">Editar Vaga</h1>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nome" class="form-label">Nome da Vaga:</label>
            <input type="text" id="nome" name="nome" value="{{ vaga.nome }}" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="faixa_salarial" class="form-label">Faixa Salarial:</label>
            <select id="faixa_salarial" name="faixa_salarial" class="form-select" required>
                <option value="1" {% if vaga.faixa_salarial == '1' %}selected{% endif %}>Até 1.000</option>
                <option value="2" {% if vaga.faixa_salarial == '2' %}selected{% endif %}>De 1.000 a 2.000</option>
                <option value="3" {% if vaga.faixa_salarial == '3' %}selected{% endif %}>De 2.000 a 3.000</option>
                <option value="4" {% if vaga.faixa_salarial == '4' %}selected{% endif %}>Acima de 3.000</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="requisitos" class="form-label">Requisitos:</label>
            <textarea id="requisitos" name="requisitos" class="form-control" required>{{ vaga.requisitos }}</textarea>
        </div>

        <div class="mb-3">
            <label for="escolaridade_minima" class="form-label">Escolaridade Mínima:</label>
            <select id="escolaridade_minima" name="escolaridade_minima" class="form-select" required>
                <option value="EF" {% if vaga.escolaridade_minima == 'EF' %}selected{% endif %}>Ensino Fundamental</option>
                <option value="EM" {% if vaga.escolaridade_minima == 'EM' %}selected{% endif %}>Ensino Médio</option>
                <option value="TEC" {% if vaga.escolaridade_minima == 'TEC' %}selected{% endif %}>Tecnólogo</option>
                <option value="ES" {% if vaga.escolaridade_minima == 'ES' %}selected{% endif %}>Ensino Superior</option>
                <option value="POS" {% if vaga.escolaridade_minima == 'POS' %}selected{% endif %}>Pós / MBA / Mestrado</option>
                <option value="DOUT" {% if vaga.escolaridade_minima == 'DOUT' %}selected{% endif %}>Doutorado</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Salvar Edições</button>
    </form>

    <a href="{% url 'pagina_apos_cadastro_empresa' %}" class="btn btn-secondary">Voltar para a home</a>
</div>
{% endblock %}

projeto_dash/app_dash/templates/empresa/vagas/lista_vagas.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1 class="display-4">Lista de Vagas</h1>
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome da Vaga</th>
                <th>Faixa Salarial</th>
                <th>Escolaridade Mínima</th>
                <th>Número de Candidatos</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for vaga in vagas %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ vaga.nome }}</td>
                <td>{{ vaga.get_faixa_salarial_display }}</td>
                <td>{{ vaga.get_escolaridade_minima_display }}</td>
                <td>{{ vaga.candidatos.count }}</td>
                <td>
                    <a href="{% url 'visualizar_candidatos' vaga.id %}" class="btn btn-primary">Visualizar Candidatos</a>
                    <a href="{% url 'editar_vaga' vaga.id %}" class="btn btn-secondary">Editar</a>
                    <a href="{% url 'deletar_vaga' vaga.id %}" class="btn btn-danger">Deletar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'nova_vaga' %}" class="btn btn-success">Criar Nova Vaga</a>
    <a href="{% url 'pagina_apos_cadastro_empresa' %}" class="btn btn-secondary">Voltar para a home</a>
</div>

    {% endblock %}

projeto_dash/app_dash/templates/empresa/vagas/nova_vaga.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nome" class="form-label">Nome da Vaga:</label>
            <input type="text" id="nome" name="nome" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="faixa_salarial" class="form-label">Faixa Salarial:</label>
            <select id="faixa_salarial" name="faixa_salarial" class="form-select" required>
                <option value="1">Até 1.000</option>
                <option value="2">De 1.000 a 2.000</option>
                <option value="3">De 2.000 a 3.000</option>
                <option value="4">Acima de 3.000</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="requisitos" class="form-label">Requisitos:</label>
            <textarea id="requisitos" name="requisitos" class="form-control" required></textarea>
        </div>

        <div class="mb-3">
            <label for="escolaridade_minima" class="form-label">Escolaridade Mínima:</label>
            <select id="escolaridade_minima" name="escolaridade_minima" class="form-select" required>
                <option value="EF">Ensino Fundamental</option>
                <option value="EM">Ensino Médio</option>
                <option value="TEC">Tecnólogo</option>
                <option value="ES">Ensino Superior</option>
                <option value="POS">Pós / MBA / Mestrado</option>
                <option value="DOUT">Doutorado</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Criar Vaga</button>
    </form>

    <a href="{% url 'pagina_apos_cadastro_empresa' %}" class="btn btn-secondary">Voltar para a home</a>
</div>
{% endblock %}

projeto_dash/app_dash/templates/empresa/vagas/visualizar_candidatos.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <h1 class="display-4">Visualizar Candidatos para a Vaga: {{ vaga.nome }}</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Pretensão Salarial</th>
                    <th>Experiência</th>
                    <th>Escolaridade</th>
                    <th>Faixa Salarial</th>
                    <th>Escolaridade</th>
                    <th>Pontuação Total</th>
                </tr>
            </thead>
            <tbody>
                {% for candidato in candidatos %}
                <tr>
                    <td>{{ candidato.user.username }}</td>
                    <td>{{ candidato.get_pretensao_salarial_display }}</td>
                    <td>{{ candidato.get_experiencia_display }}</td>
                    <td>{{ candidato.get_escolaridade_display }}</td>
                    <td>{{ candidato.pontuacao_faixa_salarial }}</td>
                    <td>{{ candidato.pontuacao_escolaridade }} </td>
                    <td>{{ candidato.pontuacao_total }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'pagina_apos_cadastro_empresa' %}" class="btn btn-primary">Voltar para a home</a>
    </div>
    
    {% endblock %}